server:
  port: 8081

spring:
  application:
    name: trip-service
  datasource:
    url: jdbc:h2:mem:tripdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

logging:
  level:
    com.trip: DEBUG
