server:
  port: 8082

spring:
  application:
    name: driver-service
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/driver_db}
      auto-index-creation: true
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}

grpc:
  server:
    port: 9092

logging:
  level:
    com.trip: DEBUG
